version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5430:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: budgety